/*****************************************************************************
 * Copyright (c) Jahan Addison
 *
 * This software is dual-licensed under the Apache License, Version 2.0 or
 * the GNU General Public License, Version 3.0 or later.
 *
 * You may use this work, in part or in whole, under the terms of either
 * license.
 *
 * See the LICENSE.Apache-v2 and LICENSE.GPL-v3 files in the project root
 * for the full text of these licenses.
 ****************************************************************************/

#include "shunting_yard.h"

#include "datatype.h"      // for make_value_type_pointer, Expres...
#include "operators.h"     // for Operator, get_precedence, is_le...
#include <credence/util.h> // for overload
#include <fmt/format.h>    // for format
#include <memory>          // for shared_ptr, make_unique, allocator
#include <ostream>         // for operator<<, basic_ostream
#include <sstream>         // for basic_ostringstream, ostringstream
#include <variant>         // for variant, visit, monostate

/****************************************************************************
 *
 * Shunting-yard queue of the RValue type in rvalue.h
 *
 * An extension to Shunting-yard to build a queue of expressions ordered by
 * operator precedence, extended for function invocation and function
 * parameters.
 *
 * I.e. a Stack-Based Virtual Machine.
 *
 * This enables semantic analysis of rvalues from the right-associative tree
 * structure originally generated by Lark.
 *
 * Example:
 *
 *   main() {
 *     auto x;
 *     x = 5 + 3 * 2;  // Respects precedence: 5 + (3 * 2) = 11
 *   }
 *
 *****************************************************************************/

/**************************************************************************
 *
 *           [~]
 *           | | (~)  (~)  (~)    /~~~~~~~~~~~~
 *        /~~~~~~~~~~~~~~~~~~~~~~~  [~_~_] |    * * * /~~~~~~~~~~~|
 *      [|  %___________________           | |~~~~~~~~            |
 *        \[___] ___   ___   ___\  No. 4   | |   A.T. & S.F.      |
 *     /// [___+/-+-\-/-+-\-/-+ \\_________|=|____________________|=
 *   //// @-=-@ \___/ \___/ \___/  @-==-@      @-==-@      @-==-@
 *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***************************************************************************/

namespace credence::language::shunting_yard {

namespace detail {

/**
 * @brief Operator precedence check of the queue and operator stack
 */
void Shunting_Yard::balance_operator_precedence(type::Operator op1)
{
    while (!operator_stack_.empty()) {
        auto op2 = operator_stack_.top();
        if ((is_left_associative(op1) &&
                get_precedence(op2) <= get_precedence(op1)) ||
            (!is_left_associative(op1) &&
                get_precedence(op2) < get_precedence(op1))) {
            queue_.emplace_back(operator_stack_.top());
            operator_stack_.pop();
        } else {
            break;
        }
    }
}

/**
 * @brief Re-balance the queue if the stack is empty
 */
void Shunting_Yard::balance_queue()
{
    if (operator_stack_.size() == 1) {
        queue_.emplace_back(operator_stack_.top());
        operator_stack_.pop();
    }
}

/**
 * @brief Shunt arguments that are PUSH'd into function calls
 */
void Shunting_Yard::shunt_argument_expressions_into_queue(
    datatype::Datatype::Function const& s)
{
    Operator_Stack operator_stack{};
    auto op1 = type::Operator::U_CALL;
    auto lhs = datatype::make_value_type_pointer(s.first);

    queue_.emplace_back(lhs);

    std::deque<Expression> parameters{};

    for (auto const& parameter : s.second) {
        auto param = datatype::make_value_type_pointer(parameter->value);
        auto name = datatype::make_lvalue(fmt::format(
            "_p{}_{}", ++(*parameter_size_), ++(*parameter_ident_)));
        auto lvalue = datatype::make_value_type_pointer(name);
        parameters.emplace_back(lvalue);
        shunt_expression_pointer_into_queue(lvalue, &operator_stack);
        shunt_expression_pointer_into_queue(param, &operator_stack);
        // param may itself carry a pending operator (e.g. "++j" leaves
        // PRE_INC on operator_stack) - drain it before this parameter's own
        // "_pN_M = param" assignment gets pushed on top of it.
        drain_operator_stack(&operator_stack);
        operator_stack.emplace(type::Operator::B_ASSIGN);
        drain_operator_stack(&operator_stack);
    }

    operator_stack.emplace(op1);

    for (auto const& param_lvalue : parameters) {
        operator_stack.emplace(type::Operator::U_PUSH);
        shunt_expression_pointer_into_queue(param_lvalue);
    }
    // PUSH/CALL is a fixed structural sequence, not a precedence relation -
    // always drain the whole stack (PUSH's in reverse-argument order, then
    // CALL) rather than balancing against it.
    drain_operator_stack(&operator_stack);
}

namespace {
////////////////////////////////////////////////////////////////////////////
// parse_from_node wraps every compound node's result in one Pointer layer
// (see RValue_Parser's m::match dispatch). A direct chain continuation - the
// "+ c" in "a * b + c", i.e. node["right"]["node"] == "relation_expression"
// with no parens - is therefore exactly one Pointer away from its real
// Relation. A genuinely parenthesized evaluated_expression is two Pointers
// away instead (the dispatch's own wrap, plus from_evaluated_expression_
// node's wrap of its inner content), so this deliberately does not unwrap
// that far - a real "(b + c)" must stay opaque to the enclosing operator.
////////////////////////////////////////////////////////////////////////////
datatype::Datatype::Relation const* as_chain_relation(
    datatype::Datatype::Pointer const& block)
{
    if (auto const* relation =
            std::get_if<datatype::Datatype::Relation>(&block->value))
        return relation->second.size() == 2 ? relation : nullptr;
    if (auto const* inner =
            std::get_if<datatype::Datatype::Pointer>(&block->value))
        if (auto const* relation =
                std::get_if<datatype::Datatype::Relation>(&(*inner)->value))
            return relation->second.size() == 2 ? relation : nullptr;
    return nullptr;
}

} // namespace

/**
 * @brief Flatten a right-associative Relation chain and shunt it left to
 * right, instead of balancing precedence against the parser's nesting
 */
void Shunting_Yard::shunt_relation_chain_into_queue(type::Operator op1,
    std::vector<datatype::Datatype::Pointer> const& blocks,
    Operator_Stack* operator_stack)
{
    Operator_Stack& operator_stack_ref =
        operator_stack != nullptr ? *operator_stack : operator_stack_;

    std::vector<datatype::Datatype::Pointer> operands{ blocks.at(0) };
    std::vector<type::Operator> ops{ op1 };
    auto rhs = blocks.at(1);

    while (auto const* relation = as_chain_relation(rhs)) {
        operands.push_back(relation->second.at(0));
        ops.push_back(relation->first);
        rhs = relation->second.at(1);
    }
    operands.push_back(rhs);

    shunt_expression_pointer_into_queue(
        datatype::make_value_type_pointer(operands.at(0)->value),
        &operator_stack_ref);

    for (std::size_t i = 0; i < ops.size(); ++i) {
        auto op = ops.at(i);
        while (!operator_stack_ref.empty() &&
               ((is_left_associative(op) &&
                    get_precedence(operator_stack_ref.top()) <=
                        get_precedence(op)) ||
                   (!is_left_associative(op) &&
                       get_precedence(operator_stack_ref.top()) <
                           get_precedence(op)))) {
            queue_.emplace_back(operator_stack_ref.top());
            operator_stack_ref.pop();
        }
        operator_stack_ref.emplace(op);
        shunt_expression_pointer_into_queue(
            datatype::make_value_type_pointer(operands.at(i + 1)->value),
            &operator_stack_ref);
    }
}

/**
 * @brief Shunt the operator stack into an ordered expression queue
 */
void Shunting_Yard::shunt_expression_pointer_into_queue(
    Expression const& pointer,
    Operator_Stack* operator_stack)
{
    Operator_Stack& operator_stack_ref =
        operator_stack != nullptr ? *operator_stack : operator_stack_;
    std::visit(
        util::overload{

            [&](std::monostate) {},
            [&](datatype::Array const&) { queue_.emplace_back(pointer); },
            [&](datatype::Literal const&) { queue_.emplace_back(pointer); },
            [&](datatype::Datatype::Pointer const& s) {
                //////////////////////////////////////////////////////////////
                // A Pointer is always a self-contained sub-expression - a
                // parenthesized evaluated_expression, or just the extra
                // wrapping layer parse_from_node's catch-all adds around a
                // Unary. Either way it must resolve fully in its own stack
                // and come out as one atomic result, never sharing the
                // enclosing stack (an inner operator here has no business
                // being compared against an outer one it isn't a sibling of).
                //////////////////////////////////////////////////////////////
                auto value = datatype::make_value_type_pointer(s->value);
                Operator_Stack nested_stack{};
                shunt_expression_pointer_into_queue(value, &nested_stack);
                drain_operator_stack(&nested_stack);
            },
            [&](datatype::Datatype::Unary const& s) {
                auto op1 = s.first;
                auto rhs = datatype::make_value_type_pointer(s.second->value);
                operator_stack_ref.emplace(op1);
                shunt_expression_pointer_into_queue(rhs, &operator_stack_ref);
            },
            [&](datatype::Datatype::LValue const&) {
                queue_.emplace_back(pointer);
            },
            [&](datatype::Datatype::Relation const& s) {
                auto op1 = s.first;
                if (s.second.size() == 2) {
                    shunt_relation_chain_into_queue(
                        op1, s.second, operator_stack);
                } else if (s.second.size() == 4) {
                    // ternary
                    operator_stack_ref.emplace(type::Operator::B_TERNARY);
                    operator_stack_ref.emplace(type::Operator::U_PUSH);
                    auto ternary_lhs = datatype::make_value_type_pointer(
                        s.second.at(2)->value);
                    auto ternary_rhs = datatype::make_value_type_pointer(
                        s.second.at(3)->value);
                    shunt_expression_pointer_into_queue(ternary_lhs);
                    shunt_expression_pointer_into_queue(ternary_rhs);
                    auto ternary_truthy = datatype::make_value_type_pointer(
                        s.second.at(0)->value);
                    operator_stack_ref.emplace(op1);
                    auto ternary_falsey = datatype::make_value_type_pointer(
                        s.second.at(1)->value);
                    shunt_expression_pointer_into_queue(ternary_truthy);
                    shunt_expression_pointer_into_queue(ternary_falsey);
                    balance_queue();
                    balance_operator_precedence(op1);
                }
            },
            [&](datatype::Datatype::Function const& s) {
                shunt_argument_expressions_into_queue(s);
            },
            [&](datatype::Datatype::Symbol const& s) {
                auto op1 = type::Operator::B_ASSIGN;
                auto lhs = datatype::make_value_type_pointer(s.first);
                auto rhs = datatype::make_value_type_pointer(s.second->value);
                shunt_expression_pointer_into_queue(lhs, &operator_stack_ref);
                operator_stack_ref.emplace(op1);
                shunt_expression_pointer_into_queue(rhs, &operator_stack_ref);
            } },
        *pointer);
}

} // namespace detail

/**
 * @brief List of expressions to queue of operators and operands
 */
std::unique_ptr<detail::Shunting_Yard::Container>
queue_from_expression_operands(Expressions const& items,
    int* parameter,
    int* identifier)
{
    detail::Shunting_Yard queue{ parameter, identifier };
    // Each item is an independent statement (merged into one array by the
    // "consecutive expression-statements share one rvalue_statement" quirk,
    // not one continuous expression) - drain fully between items so one
    // statement's pending operators can't leak in front of the next.
    for (Expression const& item : items) {
        queue.shunt_expression_pointer_into_queue(item);
        queue.drain_operator_stack();
    }

    return queue.get();
}

/**
 * @brief Single expression to queue of operators and operands
 */
std::unique_ptr<detail::Shunting_Yard::Container>
queue_from_expression_operands(Expression const& item,
    int* parameter,
    int* identifier)
{
    detail::Shunting_Yard queue{ parameter, identifier };
    queue.shunt_expression_pointer_into_queue(item);
    queue.drain_operator_stack();

    return queue.get();
}

/**
 * @brief Shunting_Yard to string of operators and operands in reverse-polish
 * notation
 */
std::string queue_of_expressions_to_string(
    detail::Shunting_Yard::Container const& queue,
    std::string_view separator)
{
    auto oss = std::ostringstream();
    for (auto& item : queue) {
        // clang-format off
        std::visit(
            util::overload{
                [&](type::Operator op) {
                    oss << type::operator_to_string(op) << " ";
                },
                [&](Expression const& s) {
                    oss << datatype::datatype_to_string(
                        *s, true, separator);
                }
            },
            item);
        // clang-format on
    }
    return oss.str();
}

/**************************************************************************
 *
 *                      (+++++++++++)
 *                 (++++)
 *              (+++)
 *            (+++)
 *           (++)
 *           [~]
 *           | | (~)  (~)  (~)    /~~~~~~~~~~~~
 *        /~~~~~~~~~~~~~~~~~~~~~~~  [~_~_] |    * * * /~~~~~~~~~~~|
 *      [|  %___________________           | |~~~~~~~~            |
 *        \[___] ___   ___   ___\  No. 4   | |   A.T. & S.F.      |
 *     /// [___+/-+-\-/-+-\-/-+ \\_________|=|____________________|=
 *   //// @-=-@ \___/ \___/ \___/  @-==-@      @-==-@      @-==-@
 *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 *------------------------------------------------
 ***************************************************************************/

} // namespace shunting_yard
