/*****************************************************************************
 * Copyright (c) Jahan Addison
 *
 * This software is dual-licensed under the Apache License, Version 2.0 or
 * the GNU General Public License, Version 3.0 or later.
 *
 * You may use this work, in part or in whole, under the terms of either
 * license.
 *
 * See the LICENSE.Apache-v2 and LICENSE.GPL-v3 files in the project root
 * for the full text of these licenses.
 ****************************************************************************/

#pragma once

#include "datatype.h"  // for Expression
#include "operators.h" // for Operator
#include <deque>       // for deque
#include <memory>      // for unique_ptr
#include <stack>       // for stack
#include <string>      // for string
#include <string_view> // for basic_string_view, string_view
#include <variant>     // for variant
#include <vector>      // for vector

/****************************************************************************
 *
 * Shunting-yard queue of the Expression type in resolver.h
 *
 * An extension to Shunting-yard to build a queue of expressions ordered by
 * operator precedence, extended for function invocation and function
 * parameters.
 *
 * I.e. a Stack-Based Virtual Machine.
 *
 * This enables semantic analysis of rvalues from the right-associative tree
 * structure originally generated by Lark.
 *
 * Example:
 *
 *   main() {
 *     auto x;
 *     x = 5 + 3 * 2;  // Respects precedence: 5 + (3 * 2) = 11
 *   }
 *
 *****************************************************************************/

/**************************************************************************
 *
 *           [~]
 *           | | (~)  (~)  (~)    /~~~~~~~~~~~~
 *        /~~~~~~~~~~~~~~~~~~~~~~~  [~_~_] |    * * * /~~~~~~~~~~~|
 *      [|  %___________________           | |~~~~~~~~            |
 *        \[___] ___   ___   ___\  No. 4   | |   A.T. & S.F.      |
 *     /// [___+/-+-\-/-+-\-/-+ \\_________|=|____________________|=
 *   //// @-=-@ \___/ \___/ \___/  @-==-@      @-==-@      @-==-@
 *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 ***************************************************************************/

namespace credence::language::shunting_yard {

using Expression = datatype::Datatype::Type_Pointer;
using Expressions = std::vector<Expression>;
using Operator_Stack = std::stack<type::Operator>;

using Type = datatype::Datatype::Type;

namespace detail {

/**
 * @brief
 *
 *  Shunting-yard queue via operator stack of expressions
 */
class Shunting_Yard
{
  public:
    Shunting_Yard() = delete;
    explicit Shunting_Yard(int* parameter_index, int* identifier_index)
        : parameter_size_(parameter_index)
        , parameter_ident_(identifier_index)
    {
    }

  public:
    using Item = std::variant<type::Operator, Expression>;
    using Container = std::deque<Item>;

    void shunt_expression_pointer_into_queue(Expression const& pointer,
        Operator_Stack* operator_stack = nullptr);
    void shunt_argument_expressions_into_queue(
        datatype::Datatype::Function const& s);

    inline std::unique_ptr<Container> get()
    {
        return std::make_unique<Container>(queue_);
    }

  private:
    void balance_operator_precedence(type::Operator op1);
    void balance_queue();
    void balance_operator_precedence(Operator_Stack* operator_stack,
        type::Operator op1);
    void balance_queue(Operator_Stack* operator_stack);

  private:
    Container queue_;

  private:
    Operator_Stack operator_stack_{};
    int* parameter_size_;
    int* parameter_ident_;
};

} // namespace detail;

std::unique_ptr<detail::Shunting_Yard::Container>
queue_from_expression_operands(Expressions const& items,
    int* parameter,
    int* identifier);

std::unique_ptr<detail::Shunting_Yard::Container>
queue_from_expression_operands(Expression const& item,
    int* parameter,
    int* identifier);

std::string queue_of_expressions_to_string(
    detail::Shunting_Yard::Container const& queue,
    std::string_view separator = ":");

} // namespace shunting_yard
